# Generated by Django 2.2.3 on 2019-07-02 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_auto_20190702_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
