# Generated by Django 2.1.9 on 2019-07-03 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_auto_20190702_0420'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='mail',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
